[keybindings]
"<Alt-q>" = "Quit"
"<Ctrl-f>" = "LoopOverTabs"
"<Ctrl-b>" = "BackLoopOverTabs"
"<Ctrl-p>" = "LoopOverTabs"
"<Ctrl-n>" = "BackLoopOverTabs"
"<Ctrl-o>" = "ProcessReplace"
"<Ctrl-l>" = "ShowHelp"
