
################################################################################

format                                       = '$all'

add_newline                                  = false

command_timeout                              = 3000

[battery]
disabled                                     = true

[character]
success_symbol                               = ' [‚àë](bold #1874CD)'
error_symbol                                 = ' [œá](bold #8B0000)'
vicmd_symbol                                 = ' [‚ùÆ](bold #C2D94C)'

[cmd_duration]
min_time                                     = 50
format                                       = ' [$duration](bold #FFC125)'

[directory]
truncation_length                            = 2
truncate_to_repo                             = true
format                                       = '[$path](#00CED1)'

[env_var]
variable                                     = 'STARSHIP_SHELL'
default                                      = 'unknown shell'
format                                       = ' [$env_value](bold #778899)'
disabled                                     = true

[hostname]
ssh_only                                     = true
format                                       = '‚ü™[$hostname](#B452CD)‚ü´ '
disabled                                     = false

[jobs]
symbol                                       = '‚à´'
number_threshold                             = 3
symbol_threshold                             = 3
style                                        = '#00CED1'

[line_break]
disabled                                     = true

[package]
format                                       = ' [ÔÜ≥](#95E6CB)  [$version](#acacac)'

[status]
format                                       = ' [$status](#8B0000)'
disabled                                     = false

[username]
disabled                                     = true

################################################################################

[shell]
bash_indicator = ' Œ≤'
fish_indicator = ' œÜ'
unknown_indicator = ' Œ∑'
zsh_indicator = ''
format = '[$indicator](#4EA24E)'
disabled = false

################################################################################

[git_branch]
truncation_length                            = 7
truncation_symbol                            = ''
format                                       = ' [[Ôêò](bold #778899) $branch](#4EA24E) '

[git_commit]
commit_hash_length                           = 4
format                                       = ' [($hash)(Ôêí)](bold #4EA24E) '

[git_state]
# progress_divider                             = '|'
# style                                        = 'bold #FFC125'

[git_status]
ahead                                        = ' [‚á°](#1874CD)[${count}](#bebebe)'
behind                                       = ' [‚á£](#8B0000)[${count}](#bebebe)'
diverged                                     = ' [ÔêÇ](#FFC125)[‚á°](#1874CD)[${ahead_count}](#bebebe)[‚á£](#8B0000)[${behind_count}](#bebebe)'
conflicted                                   = ' [Óú®](#8B0000)[${count}](#bebebe)'
untracked                                    = ' [Œ∏](#8B0000)[${count}](#bebebe)'
stashed                                      = ' [Œõ](#1874CD)[${count}](#bebebe)'
modified                                     = ' [Œî](#FFC125)[${count}](#bebebe)'
staged                                       = ' [Œ©](#95E6CB)[${count}](#bebebe)'
renamed                                      = ' [‚áå](#FFC125)[${count}](#bebebe)'
deleted                                      = ' [œá](#8B0000)[${count}](#bebebe)'

format                                       = '([\[$ahead_behind$all_status \]](bold #bebebe))'

################################################################################

[docker_context]
format                                       = ' [Ôåà $context](bold #1874CD)'

[golang]
format                                       = ' [Ô≥ë](#00CED1) [$version](bold #acacac)'

[julia]
format                                       = ' [‡ÆÉ](#9C4C9C) [$version](bold #acacac)'

[kubernetes]
format                                       = ' [‚ò∏](#00CED1) [$version](bold #acacac)'
disabled                                     = false
[kubernetes.context_aliases]
'dev.local.cluster.k8s'                      = 'dev'

[lua]
format                                       = ' [ÔÜÜ](#708090) [$version](#acacac)'

[perl]
format                                       = ' [üê™](#acacac) [$version](bold #acacac)'

[python]
pyenv_version_name                           = true
pyenv_prefix                                 = ''
format                                       = ' [Ô†ü](#228B22)'

[rlang]
format                                       = ' [¬Æ](#708090) [$version](#acacac)'
detect_files                                 = [".R"]
detect_folders                               = [".Rproj.user"]

[rust]
format                                       = ' [‚öôÔ∏è](#CD6600) [$version](#acacac)'

################################################################################
