
################################################################################

format = "$all"

################################################################################
[battery]
disabled = true

[[battery.display]]
threshold = 10
style = "bold #B22222"

[[battery.display]]
threshold = 50
style = "bold #FFC125"

################################################################################

[character]
success_symbol = "[âˆ‘](bold #6693B6)"
error_symbol = "[Ï‡](bold #8B0000)"
vicmd_symbol = "[â®](bold #C2D94C)"

################################################################################

[cmd_duration]
min_time = 200
style = "bold #FFC125"
format = "[$duration]($style) "

################################################################################

[conda]
style = "#4EA24E"

################################################################################

[directory]
truncation_length = 2
truncate_to_repo = true
style = "#00CED1"

################################################################################

[docker_context]
symbol = "ğŸ‹"
style = "bold #1874CD"

################################################################################

[env_var]
disabled = true
variable = "STARSHIP_SHELL"
default = "unknown shell"
style = "bold #778899"
format = "[$env_value]($style) "

################################################################################

[git_branch]
symbol = "[áš¶](bold #778899)"
truncation_length = 7
truncation_symbol = ""
style = "#4EA24E"
format = "[$symbol $branch]($style) "

################################################################################

[git_commit]
commit_hash_length = 4
style = "bold #4EA24E"
format = '[\($hash\)]($style) '

################################################################################

[git_state]
progress_divider = " | "
style = "bold #FFC125"

################################################################################

[git_status]
ahead = " [â‡¡](#1874CD)[${count}](#bebebe)"
behind = " [â‡£](#B22222)[${count}](#bebebe)"
diverged = " [Î¨](#FFC125)[â‡¡](#1874CD)[${ahead_count}](#bebebe)[â‡£](#B22222)[${behind_count}](#bebebe)"
conflicted = " [Î](#B22222)[${count}](#bebebe)"
untracked = " [Î¸](#B22222)[${count}](#bebebe)"
stashed = " [Î›](#1874CD)[${count}](#bebebe)"
modified = " [Î”](#FFC125)[${count}](#bebebe)"
staged = " [Î©](#95E6CB)[${count}](#bebebe)"
renamed = " [â‡Œ](#FFC125)[${count}](#bebebe)"
deleted = " [Ï‡](#B22222)[${count}](#bebebe)"

style = "bold #bebebe"
format = '([\[$ahead_behind$all_status\]]($style) )'

################################################################################

[golang]
symbol = "ğŸ¦¥"
style = "bold #95E6CB"
format = "[$symbol](#9C4C9C) [$version]($style) "

################################################################################

[hostname]
disabled = true
ssh_only = true
style = "#B452CD"
format = "âŸª[$hostname]($style)âŸ«"

#################################################################################

[java]
symbol = "â˜•"

################################################################################

[jobs]
symbol = "âˆ«"
threshold = 3
style = "#5F9EA0"

################################################################################

[julia]
style = "#95E6CB"
symbol = "à®ƒ"
format = "[$symbol](#9C4C9C) [$version]($style) "

################################################################################

[kubernetes]
symbol = "â›µ"
style = "dimmed #4EA24E"
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"

################################################################################

[line_break]
disabled = true

################################################################################

[memory_usage]

################################################################################

[package]
style = "#95E6CB"
symbol = "ğŸ“¦"
format = "$symbol [$version]($style) "

################################################################################

[python]
symbol = "ğŸ"
pyenv_version_name = true
pyenv_prefix = ""

################################################################################

[ruby]

################################################################################

[rust]
symbol = "âš™ï¸"
style = "#95E6CB"
format = "[$symbol](#CD6600) [$version]($style) "

################################################################################

[time]

################################################################################

[username]
disabled = true

################################################################################
